# Generated by Django 3.2.3 on 2022-02-28 12:39

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        UnaccentExtension()
    ]
